# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PMOD_PINS.xdc

# Block Designs: bd/kria_starter_kit/kria_starter_kit.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_starter_kit || ORIG_REF_NAME==kria_starter_kit} -quiet] -quiet

# IP: bd/kria_starter_kit/ip/kria_starter_kit_zynq_ultra_ps_e_0_0/kria_starter_kit_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_starter_kit_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==kria_starter_kit_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/kria_starter_kit/ip/kria_starter_kit_rst_ps8_0_99M_0/kria_starter_kit_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_starter_kit_rst_ps8_0_99M_0 || ORIG_REF_NAME==kria_starter_kit_rst_ps8_0_99M_0} -quiet] -quiet

# XDC: /home/stealthadmin/ECEN5713/XilinxTestFolder/PL/vivado/Example_Project/Example_Project.gen/sources_1/bd/kria_starter_kit/kria_starter_kit_ooc.xdc
